export interface QuestionItem {
  id: number;
  tense: 'presente' | 'indefinido';
  verbInfinitive: string;
  verbGroup: '-ar' | '-er' | '-ir';
  timeCue: string;
  questionEs: string;
  questionHy: string;
  answerEs: string;
  answerHy: string;
  answerVerbs: {
    stem: string;
    ending: string;
    full: string;
  }[];
  explanation: {
    es: string;
    ru: string;
    hy: string;
  };
}

export const GRAMMAR_RULES = {
  presente: {
    titleEs: 'Presente (Ներկա ժամանակ)',
    titleHy: 'Ներկա ժամանակ (Presente)',
    descEs: 'Para acciones habituales: todos los días, normalmente, siempre',
    descHy: 'Սովորական, կրկնվող գործողությունների համար (ամեն օր, սովորաբար, միշտ)',
    descRu: 'Для привычных действий: каждый день, обычно, всегда',
    cues: ['todos los días', 'normalmente', 'siempre', 'después de clase', 'por la tarde'],
    cuesHy: ['ամեն օր', 'սովորաբար', 'միշտ', 'դասից հետո', 'կեսօրից հետո'],
    groups: [
      {
        name: '-AR (entrenar, jugar, marcar)',
        endings: [
          { person: 'yo', ending: '-o', example: 'entren-o (ես մարզվում եմ)' },
          { person: 'tú', ending: '-as', example: 'entren-as (դու մարզվում ես)' },
          { person: 'él/ella', ending: '-a', example: 'entren-a (նա մարզվում է)' },
          { person: 'nosotros', ending: '-amos', example: 'entren-amos (մենք մարզվում ենք)' },
          { person: 'vosotros', ending: '-áis', example: 'entren-áis (դուք մարզվում եք)' },
          { person: 'ellos', ending: '-an', example: 'entren-an (նրանք մարզվում են)' },
        ],
      },
      {
        name: '-ER (correr, comer, aprender)',
        endings: [
          { person: 'yo', ending: '-o', example: 'corr-o (ես վազում եմ)' },
          { person: 'tú', ending: '-es', example: 'corr-es (դու վազում ես)' },
          { person: 'él/ella', ending: '-e', example: 'corr-e (նա վազում է)' },
          { person: 'nosotros', ending: '-emos', example: 'corr-emos (մենք վազում ենք)' },
          { person: 'vosotros', ending: '-éis', example: 'corr-éis (դուք վազում եք)' },
          { person: 'ellos', ending: '-en', example: 'corr-en (նրանք վազում են)' },
        ],
      },
      {
        name: '-IR (vivir, subir, decidir, recibir)',
        endings: [
          { person: 'yo', ending: '-o', example: 'viv-o (ես ապրում եմ)' },
          { person: 'tú', ending: '-es', example: 'viv-es (դու ապրում ես)' },
          { person: 'él/ella', ending: '-e', example: 'viv-e (նա ապրում է)' },
          { person: 'nosotros', ending: '-imos', example: 'viv-imos (մենք ապրում ենք)' },
          { person: 'vosotros', ending: '-ís', example: 'viv-ís (դուք ապրում եք)' },
          { person: 'ellos', ending: '-en', example: 'viv-en (նրանք ապրում են)' },
        ],
      },
    ],
  },
  indefinido: {
    titleEs: 'Pretérito Indefinido (Անցյալ ավարտված ժամանակ)',
    titleHy: 'Անցյալ կատարյալ ժամանակ (Pretérito Indefinido)',
    descEs: 'Para acciones concluidas en el pasado: ayer, anoche, el sábado pasado',
    descHy: 'Անցյալում ավարտված կոնկրետ գործողությունների համար (երեկ, անցած շաբաթ)',
    descRu: 'Для действий, завершенных в прошлом: вчера, в прошлую субботу',
    cues: ['ayer', 'anoche', 'el sábado pasado', 'la semana pasada', 'el último partido'],
    cuesHy: ['երեկ', 'երեկ գիշեր', 'անցած շաբաթ օրը', 'անցած շաբաթ', 'վերջին խաղին'],
    groups: [
      {
        name: '-AR (entrenar, jugar, marcar)',
        endings: [
          { person: 'yo', ending: '-é', example: 'entren-é (ես մարզվեցի)' },
          { person: 'tú', ending: '-aste', example: 'entren-aste (դու մարզվեցիր)' },
          { person: 'él/ella', ending: '-ó', example: 'entren-ó (նա մարզվեց)' },
          { person: 'nosotros', ending: '-amos', example: 'entren-amos (մենք մարզվեցինք)' },
          { person: 'vosotros', ending: '-asteis', example: 'entren-asteis (դուք մարզվեցիք)' },
          { person: 'ellos', ending: '-aron', example: 'entren-aron (նրանք մարզվեցին)' },
        ],
      },
      {
        name: '-ER & -IR (correr, comer, decidir, recibir)',
        endings: [
          { person: 'yo', ending: '-í', example: 'corr-í (ես վազեցի)' },
          { person: 'tú', ending: '-iste', example: 'corr-iste (դու վազեցիր)' },
          { person: 'él/ella', ending: '-ió', example: 'corr-ió (նա վազեց)' },
          { person: 'nosotros', ending: '-imos', example: 'corr-imos (մենք վազեցինք)' },
          { person: 'vosotros', ending: '-isteis', example: 'corr-isteis (դուք վազեցիք)' },
          { person: 'ellos', ending: '-ieron', example: 'corr-ieron (նրանք վազեցին)' },
        ],
      },
    ],
  },
};

export const QUESTIONS_DATA: QuestionItem[] = [
  // 1-25: PRESENTE
  {
    id: 1,
    tense: 'presente',
    verbInfinitive: 'entrenar',
    verbGroup: '-ar',
    timeCue: 'todos los días',
    questionEs: '¿Entrenas todos los días?',
    questionHy: 'Ամեն օր մարզվո՞ւմ ես։',
    answerEs: 'Sí, entreno todos los días.',
    answerHy: 'Այո, ես ամեն օր մարզվում եմ։',
    answerVerbs: [{ stem: 'entren', ending: 'o', full: 'entreno' }],
    explanation: {
      es: 'Verbo entrenar (-ar) en Presente, 1ª persona (yo) -> -o',
      ru: 'Глагол entrenar (-ar) в Presente, 1-е лицо (yo) -> -o',
      hy: 'Entrenar (-ar) բայը Presente-ում, 1-ին դեմք (yo) -> -o',
    },
  },
  {
    id: 2,
    tense: 'presente',
    verbInfinitive: 'entrenar',
    verbGroup: '-ar',
    timeCue: 'normalmente',
    questionEs: '¿Dónde entrenas normalmente?',
    questionHy: 'Սովորաբար որտե՞ղ ես մարզվում։',
    answerEs: 'Entreno en el campo de fútbol.',
    answerHy: 'Ես մարզվում եմ ֆուտբոլի դաշտում։',
    answerVerbs: [{ stem: 'entren', ending: 'o', full: 'entreno' }],
    explanation: {
      es: 'Entrenar -> entreno (yo)',
      ru: 'Обычное действие (normalmente) -> Presente (yo entreno)',
      hy: 'Սովորական գործողություն (normalmente) -> Presente (yo entreno)',
    },
  },
  {
    id: 3,
    tense: 'presente',
    verbInfinitive: 'jugar',
    verbGroup: '-ar',
    timeCue: 'después de clase',
    questionEs: '¿Juegas con tus amigos después de clase?',
    questionHy: 'Դասից հետո ընկերներիդ հետ խաղո՞ւմ ես։',
    answerEs: 'Sí, juego con mis amigos.',
    answerHy: 'Այո, ես խաղում եմ ընկերներիս հետ։',
    answerVerbs: [{ stem: 'jueg', ending: 'o', full: 'juego' }],
    explanation: {
      es: 'Verbo jugar: u -> ue en presente (yo juego)',
      ru: 'Глагол jugar с чередованием: u -> ue (yo juego)',
      hy: 'Jugar բայը փոխվում է՝ u -> ue (yo juego)',
    },
  },
  {
    id: 4,
    tense: 'presente',
    verbInfinitive: 'practicar',
    verbGroup: '-ar',
    timeCue: 'rutina',
    questionEs: '¿Practicas los penaltis?',
    questionHy: 'Մարզո՞ւմ ես պենալտիները։',
    answerEs: 'Sí, practico los penaltis.',
    answerHy: 'Այո, ես մարզում եմ պենալտիները։',
    answerVerbs: [{ stem: 'practic', ending: 'o', full: 'practico' }],
    explanation: {
      es: 'Practicar -> practico',
      ru: 'Practicar (-ar) -> practico (yo)',
      hy: 'Practicar (-ar) -> practico (yo)',
    },
  },
  {
    id: 5,
    tense: 'presente',
    verbInfinitive: 'marcar',
    verbGroup: '-ar',
    timeCue: 'frecuencia',
    questionEs: '¿Marcas muchos goles?',
    questionHy: 'Շատ գոլե՞ր ես խփում։',
    answerEs: 'Sí, marco muchos goles.',
    answerHy: 'Այո, ես շատ գոլեր եմ խփում։',
    answerVerbs: [{ stem: 'marc', ending: 'o', full: 'marco' }],
    explanation: {
      es: 'Marcar -> marco un gol',
      ru: 'Marcar (-ar) -> marco',
      hy: 'Marcar (-ar) -> marco',
    },
  },
  {
    id: 6,
    tense: 'presente',
    verbInfinitive: 'escuchar',
    verbGroup: '-ar',
    timeCue: 'siempre',
    questionEs: '¿Escuchas al entrenador?',
    questionHy: 'Լսո՞ւմ ես մարզչին։',
    answerEs: 'Sí, escucho al entrenador.',
    answerHy: 'Այո, ես լսում եմ մարզչին։',
    answerVerbs: [{ stem: 'escuch', ending: 'o', full: 'escucho' }],
    explanation: {
      es: 'Escuchar -> escucho',
      ru: 'Escuchar (-ar) -> escucho',
      hy: 'Escuchar (-ar) -> escucho',
    },
  },
  {
    id: 7,
    tense: 'presente',
    verbInfinitive: 'mirar',
    verbGroup: '-ar',
    timeCue: 'habitual',
    questionEs: '¿Mirás los partidos de otros equipos?',
    questionHy: 'Դիտո՞ւմ ես մյուս թիմերի խաղերը։',
    answerEs: 'Sí, miro muchos partidos.',
    answerHy: 'Այո, ես շատ խաղեր եմ դիտում։',
    answerVerbs: [{ stem: 'mir', ending: 'o', full: 'miro' }],
    explanation: {
      es: 'Mirar -> miro',
      ru: 'Mirar (-ar) -> miro',
      hy: 'Mirar (-ar) -> miro',
    },
  },
  {
    id: 8,
    tense: 'presente',
    verbInfinitive: 'hablar',
    verbGroup: '-ar',
    timeCue: 'durante el partido',
    questionEs: '¿Hablas con tus compañeros durante el partido?',
    questionHy: 'Խաղի ժամանակ խոսո՞ւմ ես թիմակիցներիդ հետ։',
    answerEs: 'Sí, hablo con ellos.',
    answerHy: 'Այո, ես խոսում եմ նրանց հետ։',
    answerVerbs: [{ stem: 'habl', ending: 'o', full: 'hablo' }],
    explanation: {
      es: 'Hablar -> hablo',
      ru: 'Hablar (-ar) -> hablo',
      hy: 'Hablar (-ar) -> hablo',
    },
  },
  {
    id: 9,
    tense: 'presente',
    verbInfinitive: 'preparar',
    verbGroup: '-ar',
    timeCue: 'antes del entrenamiento',
    questionEs: '¿Preparas tu mochila antes del entrenamiento?',
    questionHy: 'Մարզումից առաջ պատրաստո՞ւմ ես պայուսակդ։',
    answerEs: 'Sí, preparo mi mochila.',
    answerHy: 'Այո, ես պատրաստում եմ պայուսակս։',
    answerVerbs: [{ stem: 'prepar', ending: 'o', full: 'preparo' }],
    explanation: {
      es: 'Preparar -> preparo',
      ru: 'Preparar (-ar) -> preparo',
      hy: 'Preparar (-ar) -> preparo',
    },
  },
  {
    id: 10,
    tense: 'presente',
    verbInfinitive: 'llegar',
    verbGroup: '-ar',
    timeCue: 'siempre / temprano',
    questionEs: '¿Llegas temprano al entrenamiento?',
    questionHy: 'Մարզմանը շո՞ւտ ես հասնում։',
    answerEs: 'Sí, llego temprano.',
    answerHy: 'Այո, ես շուտ եմ հասնում։',
    answerVerbs: [{ stem: 'lleg', ending: 'o', full: 'llego' }],
    explanation: {
      es: 'Llegar -> llego',
      ru: 'Llegar (-ar) -> llego',
      hy: 'Llegar (-ar) -> llego',
    },
  },
  {
    id: 11,
    tense: 'presente',
    verbInfinitive: 'correr',
    verbGroup: '-er',
    timeCue: 'durante el partido',
    questionEs: '¿Corres mucho durante el partido?',
    questionHy: 'Խաղի ժամանակ շա՞տ ես վազում։',
    answerEs: 'Sí, corro mucho.',
    answerHy: 'Այո, ես շատ եմ վազում։',
    answerVerbs: [{ stem: 'corr', ending: 'o', full: 'corro' }],
    explanation: {
      es: 'Correr (-er) -> corro',
      ru: 'Correr (-er) -> corro (yo)',
      hy: 'Correr (-er) -> corro (yo)',
    },
  },
  {
    id: 12,
    tense: 'presente',
    verbInfinitive: 'comer',
    verbGroup: '-er',
    timeCue: 'antes del entrenamiento',
    questionEs: '¿Comes antes del entrenamiento?',
    questionHy: 'Մարզումից առաջ ուտո՞ւմ ես։',
    answerEs: 'Sí, como algo ligero.',
    answerHy: 'Այո, ես թեթև բան եմ ուտում։',
    answerVerbs: [{ stem: 'com', ending: 'o', full: 'como' }],
    explanation: {
      es: 'Comer (-er) -> como',
      ru: 'Comer (-er) -> como',
      hy: 'Comer (-er) -> como',
    },
  },
  {
    id: 13,
    tense: 'presente',
    verbInfinitive: 'beber',
    verbGroup: '-er',
    timeCue: 'durante el entrenamiento',
    questionEs: '¿Bebes agua durante el entrenamiento?',
    questionHy: 'Մարզման ժամանակ ջուր խմո՞ւմ ես։',
    answerEs: 'Sí, bebo mucha agua.',
    answerHy: 'Այո, ես շատ ջուր եմ խմում։',
    answerVerbs: [{ stem: 'beb', ending: 'o', full: 'bebo' }],
    explanation: {
      es: 'Beber (-er) -> bebo',
      ru: 'Beber (-er) -> bebo',
      hy: 'Beber (-er) -> bebo',
    },
  },
  {
    id: 14,
    tense: 'presente',
    verbInfinitive: 'aprender',
    verbGroup: '-er',
    timeCue: 'en los entrenamientos',
    questionEs: '¿Aprendes nuevas técnicas?',
    questionHy: 'Նոր տեխնիկաներ սովորո՞ւմ ես։',
    answerEs: 'Sí, aprendo nuevas técnicas.',
    answerHy: 'Այո, ես նոր տեխնիկաներ եմ սովորում։',
    answerVerbs: [{ stem: 'aprend', ending: 'o', full: 'aprendo' }],
    explanation: {
      es: 'Aprender (-er) -> aprendo',
      ru: 'Aprender (-er) -> aprendo',
      hy: 'Aprender (-er) -> aprendo',
    },
  },
  {
    id: 15,
    tense: 'presente',
    verbInfinitive: 'comprender',
    verbGroup: '-er',
    timeCue: 'en el campo',
    questionEs: '¿Comprendes las instrucciones del entrenador?',
    questionHy: 'Հասկանո՞ւմ ես մարզչի հրահանգները։',
    answerEs: 'Sí, comprendo las instrucciones.',
    answerHy: 'Այո, ես հասկանում եմ հրահանգները։',
    answerVerbs: [{ stem: 'comprend', ending: 'o', full: 'comprendo' }],
    explanation: {
      es: 'Comprender (-er) -> comprendo',
      ru: 'Comprender (-er) -> comprendo',
      hy: 'Comprender (-er) -> comprendo',
    },
  },
  {
    id: 16,
    tense: 'presente',
    verbInfinitive: 'compartir',
    verbGroup: '-ir',
    timeCue: 'en juego',
    questionEs: '¿Compartes el balón con tus compañeros?',
    questionHy: 'Գնդակը փոխանցո՞ւմ ես թիմակիցներիդ։',
    answerEs: 'Sí, comparto el balón con ellos.',
    answerHy: 'Այո, ես գնդակը փոխանցում եմ նրանց։',
    answerVerbs: [{ stem: 'compart', ending: 'o', full: 'comparto' }],
    explanation: {
      es: 'Compartir (-ir) -> comparto',
      ru: 'Compartir (-ir) -> comparto',
      hy: 'Compartir (-ir) -> comparto',
    },
  },
  {
    id: 17,
    tense: 'presente',
    verbInfinitive: 'vivir',
    verbGroup: '-ir',
    timeCue: 'habitual',
    questionEs: '¿Vives cerca del campo?',
    questionHy: 'Դաշտի մո՞տ ես ապրում։',
    answerEs: 'Sí, vivo cerca del campo.',
    answerHy: 'Այո, ես ապրում եմ դաշտի մոտ։',
    answerVerbs: [{ stem: 'viv', ending: 'o', full: 'vivo' }],
    explanation: {
      es: 'Vivir (-ir) -> vivo',
      ru: 'Vivir (-ir) -> vivo',
      hy: 'Vivir (-ir) -> vivo',
    },
  },
  {
    id: 18,
    tense: 'presente',
    verbInfinitive: 'recibir',
    verbGroup: '-ir',
    timeCue: 'en el partido',
    questionEs: '¿Recibes muchos pases?',
    questionHy: 'Շատ փոխանցումնե՞ր ես ստանում։',
    answerEs: 'Sí, recibo muchos pases.',
    answerHy: 'Այո, ես շատ փոխանցումներ եմ ստանում։',
    answerVerbs: [{ stem: 'recib', ending: 'o', full: 'recibo' }],
    explanation: {
      es: 'Recibir (-ir) -> recibo',
      ru: 'Recibir (-ir) -> recibo',
      hy: 'Recibir (-ir) -> recibo',
    },
  },
  {
    id: 19,
    tense: 'presente',
    verbInfinitive: 'subir',
    verbGroup: '-ir',
    timeCue: 'muchas veces',
    questionEs: '¿Subes al ataque muchas veces?',
    questionHy: 'Հաճա՞խ ես միանում հարձակմանը։',
    answerEs: 'Sí, subo al ataque muchas veces.',
    answerHy: 'Այո, ես հաճախ միանում եմ հարձակմանը։',
    answerVerbs: [{ stem: 'sub', ending: 'o', full: 'subo' }],
    explanation: {
      es: 'Subir (-ir) -> subo al ataque',
      ru: 'Subir (-ir) -> subo',
      hy: 'Subir (-ir) -> subo',
    },
  },
  {
    id: 20,
    tense: 'presente',
    verbInfinitive: 'decidir',
    verbGroup: '-ir',
    timeCue: 'rápido',
    questionEs: '¿Decides rápido durante el partido?',
    questionHy: 'Խաղի ժամանակ արա՞գ ես որոշում ընդունում։',
    answerEs: 'Sí, decido rápido.',
    answerHy: 'Այո, ես արագ եմ որոշում ընդունում։',
    answerVerbs: [{ stem: 'decid', ending: 'o', full: 'decido' }],
    explanation: {
      es: 'Decidir (-ir) -> decido',
      ru: 'Decidir (-ir) -> decido',
      hy: 'Decidir (-ir) -> decido',
    },
  },
  {
    id: 21,
    tense: 'presente',
    verbInfinitive: 'entrenar',
    verbGroup: '-ar',
    timeCue: 'por la tarde',
    questionEs: '¿Tu equipo entrena por la tarde?',
    questionHy: 'Քո թիմը կեսօրից հետո մարզվո՞ւմ է։',
    answerEs: 'Sí, mi equipo entrena por la tarde.',
    answerHy: 'Այո, իմ թիմը կեսօրից հետո մարզվում է։',
    answerVerbs: [{ stem: 'entren', ending: 'a', full: 'entrena' }],
    explanation: {
      es: '3ª persona singular (el equipo = él) -> -a (entrena)',
      ru: '3-е лицо ед. ч. (команда = она/он) -> entren-a',
      hy: '3-րդ դեմք եզակի (թիմը = él) -> entren-a',
    },
  },
  {
    id: 22,
    tense: 'presente',
    verbInfinitive: 'practicar',
    verbGroup: '-ar',
    timeCue: 'habitual',
    questionEs: '¿Tus compañeros practican los pases?',
    questionHy: 'Քո թիմակիցները փոխանցումներ մարզո՞ւմ են։',
    answerEs: 'Sí, practican los pases.',
    answerHy: 'Այո, նրանք մարզում են փոխանցումները։',
    answerVerbs: [{ stem: 'practic', ending: 'an', full: 'practican' }],
    explanation: {
      es: '3ª persona plural (ellos) -> -an (practican)',
      ru: '3-е лицо мн. ч. (они = compañeros) -> practic-an',
      hy: '3-րդ դեմք հոգնակի (նրանք) -> practic-an',
    },
  },
  {
    id: 23,
    tense: 'presente',
    verbInfinitive: 'entrenar',
    verbGroup: '-ar',
    timeCue: 'juntos',
    questionEs: '¿Vosotros entrenáis juntos?',
    questionHy: 'Դուք միասի՞ն եք մարզվում։',
    answerEs: 'Sí, entrenamos juntos.',
    answerHy: 'Այո, մենք միասին ենք մարզվում։',
    answerVerbs: [{ stem: 'entren', ending: 'amos', full: 'entrenamos' }],
    explanation: {
      es: 'Responde nosotros -> -amos (entrenamos)',
      ru: 'Вопрос к vosotros, ответ от nosotros -> entren-amos',
      hy: 'Հարցը vosostros-ին, պատասխանը nosotros-ով -> entren-amos',
    },
  },
  {
    id: 24,
    tense: 'presente',
    verbInfinitive: 'explicar',
    verbGroup: '-ar',
    timeCue: 'en el campo',
    questionEs: '¿El entrenador explica las jugadas?',
    questionHy: 'Մարզիչը բացատրո՞ւմ է խաղային գործողությունները։',
    answerEs: 'Sí, explica las jugadas.',
    answerHy: 'Այո, նա բացատրում է խաղային գործողությունները։',
    answerVerbs: [{ stem: 'explic', ending: 'a', full: 'explica' }],
    explanation: {
      es: '3ª persona (el entrenador = él) -> -a (explica)',
      ru: '3-е лицо (тренер = él) -> explic-a',
      hy: '3-րդ դեմք (մարզիչը = él) -> explic-a',
    },
  },
  {
    id: 25,
    tense: 'presente',
    verbInfinitive: 'descansar / hablar',
    verbGroup: '-ar',
    timeCue: 'cuando termina',
    questionEs: '¿Qué haces cuando termina el entrenamiento?',
    questionHy: 'Ի՞նչ ես անում, երբ մարզումն ավարտվում է։',
    answerEs: 'Descanso y hablo con mis compañeros.',
    answerHy: 'Ես հանգստանում եմ և խոսում եմ թիմակիցներիս հետ։',
    answerVerbs: [
      { stem: 'descans', ending: 'o', full: 'descanso' },
      { stem: 'habl', ending: 'o', full: 'hablo' },
    ],
    explanation: {
      es: 'Dos verbos en presente: descanso + hablo',
      ru: 'Два глагола в Presente: descans-o и habl-o',
      hy: 'Երկու բայ Presente-ում՝ descans-o և habl-o',
    },
  },

  // 26-50: PRETÉRITO INDEFINIDO
  {
    id: 26,
    tense: 'indefinido',
    verbInfinitive: 'entrenar',
    verbGroup: '-ar',
    timeCue: 'ayer',
    questionEs: '¿Entrenaste ayer?',
    questionHy: 'Երեկ մարզվե՞լ ես։',
    answerEs: 'Sí, entrené ayer.',
    answerHy: 'Այո, ես երեկ մարզվեցի։',
    answerVerbs: [{ stem: 'entren', ending: 'é', full: 'entrené' }],
    explanation: {
      es: 'Ayer -> Indefinido. Verbo -ar (yo) -> -é con tilde (entrené)',
      ru: 'Вчера (ayer) -> Indefinido. Глагол -ar (yo) -> -é (entrené)',
      hy: 'Երեկ (ayer) -> Indefinido. -AR բայ (yo) -> -é (entrené)',
    },
  },
  {
    id: 27,
    tense: 'indefinido',
    verbInfinitive: 'entrenar',
    verbGroup: '-ar',
    timeCue: 'ayer',
    questionEs: '¿Dónde entrenaste ayer?',
    questionHy: 'Երեկ որտե՞ղ մարզվեցիր։',
    answerEs: 'Entrené en el campo.',
    answerHy: 'Ես մարզվեցի դաշտում։',
    answerVerbs: [{ stem: 'entren', ending: 'é', full: 'entrené' }],
    explanation: {
      es: 'Ayer -> entrené',
      ru: 'Вчера -> entrené (yo)',
      hy: 'Երեկ -> entrené (yo)',
    },
  },
  {
    id: 28,
    tense: 'indefinido',
    verbInfinitive: 'jugar',
    verbGroup: '-ar',
    timeCue: 'el sábado',
    questionEs: '¿Jugaste un partido el sábado?',
    questionHy: 'Շաբաթ օրը խաղ խաղացի՞ր։',
    answerEs: 'Sí, jugué un partido.',
    answerHy: 'Այո, ես խաղ խաղացի։',
    answerVerbs: [{ stem: 'jug', ending: 'ué', full: 'jugué' }],
    explanation: {
      es: 'Jugar en indefinido yo -> jugué (ortografía: g -> gu delante de e)',
      ru: 'Jugar в Indefinido (yo) -> jugué (g переходит в gu перед e)',
      hy: 'Jugar-ը Indefinido (yo)-ում -> jugué (g-ն դառնում է gu՝ e-ից առաջ)',
    },
  },
  {
    id: 29,
    tense: 'indefinido',
    verbInfinitive: 'marcar',
    verbGroup: '-ar',
    timeCue: 'el partido pasado',
    questionEs: '¿Marcaste algún gol?',
    questionHy: 'Գոլ խփեցի՞ր։',
    answerEs: 'Sí, marqué un gol.',
    answerHy: 'Այո, ես մեկ գոլ խփեցի։',
    answerVerbs: [{ stem: 'marq', ending: 'ué', full: 'marqué' }],
    explanation: {
      es: 'Marcar en indefinido yo -> marqué (ortografía: c -> qu delante de e)',
      ru: 'Marcar в Indefinido (yo) -> marqué (c переходит в qu перед e)',
      hy: 'Marcar-ը Indefinido (yo)-ում -> marqué (c-ն դառնում է qu՝ e-ից առաջ)',
    },
  },
  {
    id: 30,
    tense: 'indefinido',
    verbInfinitive: 'practicar',
    verbGroup: '-ar',
    timeCue: 'ayer',
    questionEs: '¿Practicaste los penaltis ayer?',
    questionHy: 'Երեկ պենալտիներ մարզեցի՞ր։',
    answerEs: 'Sí, practiqué los penaltis.',
    answerHy: 'Այո, ես պենալտիներ մարզեցի։',
    answerVerbs: [{ stem: 'practiq', ending: 'ué', full: 'practiqué' }],
    explanation: {
      es: 'Practicar en indefinido yo -> practiqué (c -> qu)',
      ru: 'Practicar в Indefinido (yo) -> practiqué (c -> qu)',
      hy: 'Practicar-ը Indefinido (yo)-ում -> practiqué (c -> qu)',
    },
  },
  {
    id: 31,
    tense: 'indefinido',
    verbInfinitive: 'hablar',
    verbGroup: '-ar',
    timeCue: 'después del partido',
    questionEs: '¿Hablaste con tu entrenador después del partido?',
    questionHy: 'Խաղից հետո խոսեցի՞ր մարզչիդ հետ։',
    answerEs: 'Sí, hablé con mi entrenador.',
    answerHy: 'Այո, ես խոսեցի մարզչիս հետ։',
    answerVerbs: [{ stem: 'habl', ending: 'é', full: 'hablé' }],
    explanation: {
      es: 'Hablar -> hablé',
      ru: 'Hablar (-ar) -> hablé',
      hy: 'Hablar (-ar) -> hablé',
    },
  },
  {
    id: 32,
    tense: 'indefinido',
    verbInfinitive: 'escuchar',
    verbGroup: '-ar',
    timeCue: 'en el partido pasado',
    questionEs: '¿Escuchaste las instrucciones?',
    questionHy: 'Լսեցի՞ր հրահանգները։',
    answerEs: 'Sí, escuché todas las instrucciones.',
    answerHy: 'Այո, ես լսեցի բոլոր հրահանգները։',
    answerVerbs: [{ stem: 'escuch', ending: 'é', full: 'escuché' }],
    explanation: {
      es: 'Escuchar -> escuché',
      ru: 'Escuchar (-ar) -> escuché',
      hy: 'Escuchar (-ar) -> escuché',
    },
  },
  {
    id: 33,
    tense: 'indefinido',
    verbInfinitive: 'llegar',
    verbGroup: '-ar',
    timeCue: 'al campo',
    questionEs: '¿Llegaste temprano al campo?',
    questionHy: 'Դաշտ շո՞ւտ հասար։',
    answerEs: 'Sí, llegué temprano.',
    answerHy: 'Այո, ես շուտ հասա։',
    answerVerbs: [{ stem: 'lleg', ending: 'ué', full: 'llegué' }],
    explanation: {
      es: 'Llegar -> llegué (g -> gu)',
      ru: 'Llegar (-ar) -> llegué (g -> gu)',
      hy: 'Llegar (-ar) -> llegué (g -> gu)',
    },
  },
  {
    id: 34,
    tense: 'indefinido',
    verbInfinitive: 'preparar',
    verbGroup: '-ar',
    timeCue: 'antes del partido',
    questionEs: '¿Preparaste tu mochila antes del partido?',
    questionHy: 'Խաղից առաջ պատրաստեցի՞ր պայուսակդ։',
    answerEs: 'Sí, preparé mi mochila.',
    answerHy: 'Այո, ես պատրաստեցի պայուսակս։',
    answerVerbs: [{ stem: 'prepar', ending: 'é', full: 'preparé' }],
    explanation: {
      es: 'Preparar -> preparé',
      ru: 'Preparar (-ar) -> preparé',
      hy: 'Preparar (-ar) -> preparé',
    },
  },
  {
    id: 35,
    tense: 'indefinido',
    verbInfinitive: 'celebrar',
    verbGroup: '-ar',
    timeCue: 'tras el gol',
    questionEs: '¿Celebraste el gol?',
    questionHy: 'Գոլը տոնեցի՞ր։',
    answerEs: 'Sí, celebré el gol con mis compañeros.',
    answerHy: 'Այո, ես գոլը տոնեցի թիմակիցներիս հետ։',
    answerVerbs: [{ stem: 'celebr', ending: 'é', full: 'celebré' }],
    explanation: {
      es: 'Celebrar -> celebré',
      ru: 'Celebrar (-ar) -> celebré',
      hy: 'Celebrar (-ar) -> celebré',
    },
  },
  {
    id: 36,
    tense: 'indefinido',
    verbInfinitive: 'correr',
    verbGroup: '-er',
    timeCue: 'durante el partido',
    questionEs: '¿Corriste mucho durante el partido?',
    questionHy: 'Խաղի ժամանակ շա՞տ վազեցիր։',
    answerEs: 'Sí, corrí mucho.',
    answerHy: 'Այո, ես շատ վազեցի։',
    answerVerbs: [{ stem: 'corr', ending: 'í', full: 'corrí' }],
    explanation: {
      es: 'Verbo -er en Indefinido (yo) -> -í con tilde (corrí)',
      ru: 'Глагол -er в Indefinido (yo) -> -í (corrí)',
      hy: '-ER բայը Indefinido (yo)-ում -> -í (corrí)',
    },
  },
  {
    id: 37,
    tense: 'indefinido',
    verbInfinitive: 'comer',
    verbGroup: '-er',
    timeCue: 'antes del partido',
    questionEs: '¿Comiste antes del partido?',
    questionHy: 'Խաղից առաջ կերա՞ր։',
    answerEs: 'Sí, comí antes del partido.',
    answerHy: 'Այո, ես խաղից առաջ կերա։',
    answerVerbs: [{ stem: 'com', ending: 'í', full: 'comí' }],
    explanation: {
      es: 'Comer (-er) -> comí',
      ru: 'Comer (-er) -> comí',
      hy: 'Comer (-er) -> comí',
    },
  },
  {
    id: 38,
    tense: 'indefinido',
    verbInfinitive: 'beber',
    verbGroup: '-er',
    timeCue: 'en el descanso',
    questionEs: '¿Bebiste suficiente agua?',
    questionHy: 'Բավականաչափ ջուր խմեցի՞ր։',
    answerEs: 'Sí, bebí mucha agua.',
    answerHy: 'Այո, ես շատ ջուր խմեցի։',
    answerVerbs: [{ stem: 'beb', ending: 'í', full: 'bebí' }],
    explanation: {
      es: 'Beber (-er) -> bebí',
      ru: 'Beber (-er) -> bebí',
      hy: 'Beber (-er) -> bebí',
    },
  },
  {
    id: 39,
    tense: 'indefinido',
    verbInfinitive: 'aprender',
    verbGroup: '-er',
    timeCue: 'en el entrenamiento',
    questionEs: '¿Aprendiste algo nuevo en el entrenamiento?',
    questionHy: 'Մարզման ժամանակ նոր բան սովորեցի՞ր։',
    answerEs: 'Sí, aprendí una técnica nueva.',
    answerHy: 'Այո, ես նոր տեխնիկա սովորեցի։',
    answerVerbs: [{ stem: 'aprend', ending: 'í', full: 'aprendí' }],
    explanation: {
      es: 'Aprender (-er) -> aprendí',
      ru: 'Aprender (-er) -> aprendí',
      hy: 'Aprender (-er) -> aprendí',
    },
  },
  {
    id: 40,
    tense: 'indefinido',
    verbInfinitive: 'comprender',
    verbGroup: '-er',
    timeCue: 'la charla táctica',
    questionEs: '¿Comprendiste lo que explicó el entrenador?',
    questionHy: 'Հասկացա՞ր մարզչի բացատրածը։',
    answerEs: 'Sí, comprendí todo.',
    answerHy: 'Այո, ես ամեն ինչ հասկացա։',
    answerVerbs: [{ stem: 'comprend', ending: 'í', full: 'comprendí' }],
    explanation: {
      es: 'Comprender (-er) -> comprendí',
      ru: 'Comprender (-er) -> comprendí',
      hy: 'Comprender (-er) -> comprendí',
    },
  },
  {
    id: 41,
    tense: 'indefinido',
    verbInfinitive: 'recibir',
    verbGroup: '-ir',
    timeCue: 'en el partido',
    questionEs: '¿Recibiste muchos pases?',
    questionHy: 'Շատ փոխանցումներ ստացա՞ր։',
    answerEs: 'Sí, recibí muchos pases.',
    answerHy: 'Այո, ես շատ փոխանցումներ ստացա։',
    answerVerbs: [{ stem: 'recib', ending: 'í', full: 'recibí' }],
    explanation: {
      es: 'Verbo -ir en Indefinido (yo) -> -í (recibí)',
      ru: 'Глагол -ir в Indefinido (yo) -> -í (recibí)',
      hy: '-IR բայը Indefinido (yo)-ում -> -í (recibí)',
    },
  },
  {
    id: 42,
    tense: 'indefinido',
    verbInfinitive: 'decidir',
    verbGroup: '-ir',
    timeCue: 'en la jugada',
    questionEs: '¿Decidiste tirar a portería?',
    questionHy: 'Որոշեցի՞ր հարվածել դարպասին։',
    answerEs: 'Sí, decidí tirar a portería.',
    answerHy: 'Այո, ես որոշեցի հարվածել դարպասին։',
    answerVerbs: [{ stem: 'decid', ending: 'í', full: 'decidí' }],
    explanation: {
      es: 'Decidir (-ir) -> decidí',
      ru: 'Decidir (-ir) -> decidí',
      hy: 'Decidir (-ir) -> decidí',
    },
  },
  {
    id: 43,
    tense: 'indefinido',
    verbInfinitive: 'ganar',
    verbGroup: '-ar',
    timeCue: 'el partido',
    questionEs: '¿Tu equipo ganó el partido?',
    questionHy: 'Քո թիմը հաղթե՞ց խաղը։',
    answerEs: 'Sí, mi equipo ganó el partido.',
    answerHy: 'Այո, իմ թիմը հաղթեց խաղը։',
    answerVerbs: [{ stem: 'gan', ending: 'ó', full: 'ganó' }],
    explanation: {
      es: '3ª persona (el equipo = él) -> -ó (ganó)',
      ru: '3-е лицо (команда = он) -> gan-ó',
      hy: '3-րդ դեմք (թիմը = él) -> gan-ó',
    },
  },
  {
    id: 44,
    tense: 'indefinido',
    verbInfinitive: 'marcar',
    verbGroup: '-ar',
    timeCue: 'el partido',
    questionEs: '¿Tu compañero marcó un gol?',
    questionHy: 'Քո թիմակիցը գոլ խփե՞ց։',
    answerEs: 'Sí, marcó un gol.',
    answerHy: 'Այո, նա գոլ խփեց։',
    answerVerbs: [{ stem: 'marc', ending: 'ó', full: 'marcó' }],
    explanation: {
      es: '3ª persona (tu compañero = él) -> -ó (marcó)',
      ru: '3-е лицо (товарищ = él) -> marc-ó',
      hy: '3-րդ դեմք (ընկերը = él) -> marc-ó',
    },
  },
  {
    id: 45,
    tense: 'indefinido',
    verbInfinitive: 'explicar',
    verbGroup: '-ar',
    timeCue: 'antes del partido',
    questionEs: '¿El entrenador explicó una nueva táctica?',
    questionHy: 'Մարզիչը նոր տակտիկա բացատրե՞ց։',
    answerEs: 'Sí, explicó una nueva táctica.',
    answerHy: 'Այո, նա նոր տակտիկա բացատրեց։',
    answerVerbs: [{ stem: 'explic', ending: 'ó', full: 'explicó' }],
    explanation: {
      es: '3ª persona (el entrenador = él) -> -ó (explicó)',
      ru: '3-е лицо (тренер = él) -> explic-ó',
      hy: '3-րդ դեմք (մարզիչը = él) -> explic-ó',
    },
  },
  {
    id: 46,
    tense: 'indefinido',
    verbInfinitive: 'entrenar',
    verbGroup: '-ar',
    timeCue: 'ayer / dos horas',
    questionEs: '¿Vosotros entrenasteis ayer?',
    questionHy: 'Դուք երեկ մարզվեցի՞ք։',
    answerEs: 'Sí, entrenamos durante dos horas.',
    answerHy: 'Այո, մենք երկու ժամ մարզվեցինք։',
    answerVerbs: [{ stem: 'entren', ending: 'amos', full: 'entrenamos' }],
    explanation: {
      es: 'Respuesta en nosotros -> entrenamos (¡igual en presente e indefinido para -ar!)',
      ru: 'Ответ от nosotros -> entren-amos (форма -amos совпадает в Presente и Indefinido!)',
      hy: 'Պատասխանը nosotros-ով -> entren-amos (համընկնում է Presente-ի և Indefinido-ի համար)',
    },
  },
  {
    id: 47,
    tense: 'indefinido',
    verbInfinitive: 'jugar',
    verbGroup: '-ar',
    timeCue: 'el último partido',
    questionEs: '¿Jugasteis bien el último partido?',
    questionHy: 'Վերջին խաղում լա՞վ խաղացիք։',
    answerEs: 'Sí, jugamos muy bien.',
    answerHy: 'Այո, մենք շատ լավ խաղացինք։',
    answerVerbs: [{ stem: 'jug', ending: 'amos', full: 'jugamos' }],
    explanation: {
      es: 'Nosotros -> jugamos (el último partido indica pasado)',
      ru: 'Nosotros -> jugamos (el último partido указывает на прошлое)',
      hy: 'Nosotros -> jugamos (el último partido ցույց է տալիս անցյալ)',
    },
  },
  {
    id: 48,
    tense: 'indefinido',
    verbInfinitive: 'marcar',
    verbGroup: '-ar',
    timeCue: 'el partido',
    questionEs: '¿Tus compañeros marcaron goles?',
    questionHy: 'Քո թիմակիցները գոլեր խփեցի՞ն։',
    answerEs: 'Sí, marcaron tres goles.',
    answerHy: 'Այո, նրանք երեք գոլ խփեցին։',
    answerVerbs: [{ stem: 'marc', ending: 'aron', full: 'marcaron' }],
    explanation: {
      es: '3ª persona plural (ellos) -> -aron (marcaron)',
      ru: '3-е лицо мн. ч. (они = compañeros) -> marc-aron',
      hy: '3-րդ դեմք հոգնակի (նրանք) -> marc-aron',
    },
  },
  {
    id: 49,
    tense: 'indefinido',
    verbInfinitive: 'celebrar',
    verbGroup: '-ar',
    timeCue: 'después del partido',
    questionEs: '¿Celebraron la victoria después del partido?',
    questionHy: 'Նրանք խաղից հետո նշեցի՞ն հաղթանակը։',
    answerEs: 'Sí, celebraron la victoria.',
    answerHy: 'Այո, նրանք նշեցին հաղթանակը։',
    answerVerbs: [{ stem: 'celebr', ending: 'aron', full: 'celebraron' }],
    explanation: {
      es: '3ª persona plural (ellos) -> -aron (celebraron)',
      ru: '3-е лицо мн. ч. (они) -> celebr-aron',
      hy: '3-րդ դեմք հոգնակի (նրանք) -> celebr-aron',
    },
  },
  {
    id: 50,
    tense: 'indefinido',
    verbInfinitive: 'descansar / cenar / hablar',
    verbGroup: '-ar',
    timeCue: 'después del entrenamiento',
    questionEs: '¿Qué hiciste después del entrenamiento?',
    questionHy: 'Ի՞նչ արեցիր մարզումից հետո։',
    answerEs: 'Descansé, cené y hablé con mi familia.',
    answerHy: 'Ես հանգստացա, ընթրեցի և խոսեցի ընտանիքիս հետ։',
    answerVerbs: [
      { stem: 'descans', ending: 'é', full: 'descansé' },
      { stem: 'cen', ending: 'é', full: 'cené' },
      { stem: 'habl', ending: 'é', full: 'hablé' },
    ],
    explanation: {
      es: 'Tres verbos en indefinido (yo): descansé, cené, hablé',
      ru: 'Три глагола в Indefinido (yo): descans-é, cen-é, habl-é',
      hy: 'Երեք բայ Indefinido (yo)-ում՝ descans-é, cen-é, habl-é',
    },
  },
];
